spring:
  application:
    name: techstore
  config:
    import: nacos:techstore.yml?refresh=true
  cloud:
    nacos:
      config:
        server-addr: ${NACOS_ADDR:119.29.145.64:8848}
        username: nacos
        password: nacos
